version: '3.8'

services:
  webserver:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: test_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db:
